app = "westernloudouncoop"
primary_region = "iad"

[build]
dockerfile = "Dockerfile"

[env]
DATABASE_PATH = "/data/preschool.db"
PORT = "8080"
PRODUCTION = "1"
STATIC_DIR = "./static"
UPLOADS_DIR = "/data/uploads"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_080
min_machines_running = 0

[[http_service.checks]]
  interval = "10s"
  timeout = "2s"
  grace_period = "5s"
  method = "GET"
  path = "/health"

[[mounts]]
destination = "/data"
source = "wlpc_data"

[[vm]]
memory = "256mb"
size = "shared-cpu-1x"
